# Name of the pipeline
name: ato-typescript-playwright-esm-pnpm

# Pipeline execution rules
on:
  # schedule:                        # Run pipeline when triggered by a scheduled event
  #   - cron: '0 0 */3 * *'          # Run pipeline every 3rd day at midnight UTC
  workflow_dispatch:                 # Run pipeline when triggered manually from the web UI
    inputs:
      ALLURE_JOB_RUN_ID:
        description: "ALLURE_JOB_RUN_ID - service parameter, leave blank"
        required: false
        default: ""
      ALLURE_USERNAME:
        description: "ALLURE_USERNAME - service parameter, leave blank"
        required: false
        default: ""
      # BROWSER configuration is defined in playwright.config.ts
      #
      # BROWSER: 
      #  description: "Specify the browser"
      #  required: true
      #  default: "Chrome"                                              # Default browser
      #  type: choice
      #  options:                                                       # Available options
      #    - "Chrome"
      #    - "Firefox"
      #    - "Safari"
      #
      HOST: 
        description: "Specify the environment host"
        required: true
        default: "demo.testops.cloud"                                   # Default environment host
        type: choice
        options:                                                        # Available options
          - "demo.testops.cloud"
          - "production.testops.cloud"
          - "qa.testops.cloud"
          - "testing.testops.cloud"
          - "staging.testops.cloud"
      # OS configuration is defined in playwright.config.ts
      #
      # OS: 
      #  description: "Specify the operating system"
      #  required: true
      #  default: "macOS"                                               # Default operating system
      #  type: choice
      #  options:                                                       # Available options
      #    - "Linux"
      #    - "macOS"
      #    - "Windows"
      #
      VERSION:
        description: "Specify the software version under test"
        required: true
        default: "25.1.0"                                               # Default software version under test

# Global environment variables
env:
  ALLURE_ENDPOINT: "https://demo.testops.cloud/"                                                # Allure TestOps endpoint URL for submitting test results
  ALLURE_PROJECT_ID: "3111"                                                                     # Allure TestOps project ID for submitting test results
  ALLURE_RESULTS: "./allure-results"                                                            # Directory where test result files will be stored
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}                                                     # Authentication token for Allure TestOps (secured environment variable)
  ALLURE_LAUNCH_NAME_WITHOUT_TIME: "TypeScript/Playwright - #${{ github.run_number }}"          # Base Allure TestOps launch name (without timestamp)
  BRANCH: ${{ github.ref_name }}                                                                # Current Git branch name 
  HOME: /root                                                                                   # Firefox doesn’t allow running as root unless $HOME is explicitly set to /root

jobs:
  # Job for timestamp parsing
  timestamp:
    name: timestamp_parsing
    runs-on: ubuntu-latest
    outputs:
      parsed_timestamp: ${{ steps.set-output.outputs.PARSED_TIMESTAMP }}
    steps:
      - name: Set Timestamp
        id: set-output
        run: |
          PARSED_TIMESTAMP=$(date -d "${{ github.event.head_commit.timestamp }} +3 hours" +"%Y.%m.%d - %H:%M:%S")
          echo "PARSED_TIMESTAMP=$PARSED_TIMESTAMP" >> $GITHUB_OUTPUT
  
  # Job for tests execution
  tests:
    name: tests_execution
    needs: timestamp
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.42.1-jammy          # Use official Playwright Docker image
    steps:
      - uses: actions/checkout@v3

      - name: 📦 Enable corepack and install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8.15.4 --activate
          pnpm install
          npx playwright install

      - name: ⬇️ Downloading allurectl...
        run: |
          wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64 -O ./allurectl
          chmod +x ./allurectl

      - name: ▶️ Running tests...
        run: |
          ./allurectl watch pnpm test
        env:
          ALLURE_LAUNCH_NAME: "${{ env.ALLURE_LAUNCH_NAME_WITHOUT_TIME }} - ${{ needs.timestamp.outputs.parsed_timestamp }}"          # Set full Allure TestOps launch name (with timestamp)
