name: ato-typescript-playwright-esm-pnpm

on:
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: "ALLURE_JOB_RUN_ID - service parameter (leave blank)"
        required: false
        default: ""
      ALLURE_USERNAME:
        description: "ALLURE_USERNAME - service parameter (leave blank)"
        required: false
        default: ""
      HOST: 
        required: true
        default: "demo.testops.cloud"
      VERSION:
        required: true
        default: "25.1.0"

env:
  ALLURE_ENDPOINT: "https://demo.testops.cloud/"
  ALLURE_PROJECT_ID: "3111"
  ALLURE_RESULTS: "./allure-results"
  ALLURE_LAUNCH_NAME_WITHOUT_TIME: "TypeScript/Playwright - #${{ github.run_number }}"
  BRANCH: ${{ github.ref_name }} 

jobs:
  timestamp:
    name: Parse Timestamp
    runs-on: ubuntu-latest
    outputs:
      parsed_timestamp: ${{ steps.set-output.outputs.PARSED_TIMESTAMP }}
    steps:
      - name: Set Timestamp
        id: set-output
        run: |
          PARSED_TIMESTAMP=$(date -d "${{ github.event.head_commit.timestamp }} +3 hours" +"%Y.%m.%d - %H:%M:%S")
          echo "PARSED_TIMESTAMP=$PARSED_TIMESTAMP" >> $GITHUB_OUTPUT
  
  tests:
    name: Run Tests
    needs: timestamp
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.42.1-jammy
    steps:
      - uses: actions/checkout@v3

      - name: Enable corepack and install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8.15.4 --activate
          pnpm install
          npx playwright install

      - name: Download allurectl
        run: |
          wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64 -O ./allurectl
          chmod +x ./allurectl

      - name: Run Playwright tests and upload to Allure
        env:
          ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
          ALLURE_LAUNCH_NAME: "${{ env.ALLURE_LAUNCH_NAME_WITHOUT_TIME }} - ${{ needs.timestamp.outputs.parsed_timestamp }}"
        run: |
          ./allurectl watch pnpm test
